stages:
- name: test_stage
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: npm start
  - runScriptConfig:
      image: node:latest
      shellScript: |-
        npm install
        npm test
    env:
      SERVER: nodeserver
- name: package_stage
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example/App:v1
      pushRemote: true
      registry: index.docker.io
timeout: 60
notification: {}
